### ISSUE TITLE
Alignment ignored in resource_adaptor?

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/container#107]
`resource_adaptor` rebinds the caller's _Allocator_ type to `char`, which destroys the alignment information. Then in `allocate` it ignores the `alignment` parameter. Is this the right thing to do?

**Comment by igaztanaga** [comment]
You are right. operator new is guaranteed to be aligned to any type without extended alignment attributes, but the char-rebound Allocator type could only guarantee byte alignment. I'll review design alternatives to guarantee aligned allocations.

**Comment by vinniefalco** [comment]
I'm not really happy with the polymorphic allocator / memory resource design but that's not Boost.Container's problem. How do you implement a reference-counted memory resource? Seems there's no way.

**Comment by igaztanaga** [comment]
memory_resource isn't thought for that use case, many would not like to pay for a reference-counted design that they won't use ;-)

**Comment by igaztanaga** [comment]
Thanks for the bug report!
