### ISSUE TITLE
Missing files breaks develop documentation build

### ISSUE THREAD

**Issue by glenfe** [boostorg/container#119]
The following two commits have broken the build of all develop documentation at https://www.boost.org/doc/libs/develop/:
* 4c348af1eb1290f9f20f277f76266df16f91b5ea
* 5d96b11fe0d8351f2a9ee3960f5c2da7ba9b6642

They reference the following files which don't exist:
* example/doc_custom_static_vector.cpp
* example/doc_custom_small_vector.cpp

> container.qbk:744: error: Unable to find file: ../example/doc_custom_static_vector.cpp
> container.qbk:771: error: Unable to find file: ../example/doc_custom_small_vector.cpp
> Error: Error count: 2.

**Comment by pdimov** [comment]
Please fix.

**Comment by igaztanaga** [comment]
Sorry and thanks for the report.
