### ISSUE TITLE
flat_set of flat_set has allocator type void

### ISSUE THREAD

**Issue by thebrandre** [boostorg/container#124]
Click [here](https://godbolt.org/z/WaUw6A) for a minimal example on compiler explorer.
The snippet works with boost-1.69 but not with boost-1.70. That's the only difference between the two compiler windows (a click on 'output' reveals the error message).
This seems to be related to issue #120 ... so it may already be fixed. Can anyone confirm?

**Comment by igaztanaga** [comment]
Yes, it's fixed.
