### ISSUE TITLE
flat_map doc misleading complexity

### ISSUE THREAD

**Issue by mglisse** [boostorg/container#125]
Hello,
the documentation of some flat_map operations has a misleading complexity guarantee. For instance, `operator[]` or `insert_or_assign` say "logarithmic", but while the number of comparisons is logarithmic, the number of move/copy can be linear. `emplace` kind of acknowledges this ("Logarithmic search time plus linear insertion to the elements with bigger keys than x"), although it is still wrong if the capacity is exceeded.

**Comment by igaztanaga** [comment]
Many thanks for the report!
