### ISSUE TITLE
Use std::contiguous_iterator_tag if available

### ISSUE THREAD

**Issue by patlefort** [boostorg/container#150]
vector's iterator should provide a std::iterator_traits specialization with iterator_concept = std::contiguous_iterator_tag if it's available. Otherwise, it is for example unusable with std::span if you pass it as a range.

**Comment by igaztanaga** [comment]
Thanks for the request. Tested in GCC and MSVC, it will surely need additional tweaks for Clang/C++ depending on LWG3446 resolution implementation in libc++.
