### ISSUE TITLE
`splice`, `sort` etc for `stable_vector`

### ISSUE THREAD

**Issue by dmsteck** [boostorg/container#170]
I wonder if `stable_vector` could benefit from `list`-like operations such as splicing, sorting, reversing etc. while preserving pointers and iterators. These would generally work by transforming the pointer vector and updating the "up" pointers.

It might also be interesting to add a facility for swapping two nodes while preserving their respective pointers and iterators. (For `std::list`, this is usually done by splicing, but for `stable_vector` that could be prohibitively expensive as it would mean allocating a temporary.)

Let me know if this sounds reasonable. Happy to cook up a PR.

**Comment by igaztanaga** [comment]
Looks interesting. Happy to review a PR ;-)

**Comment by igaztanaga** [comment]
Closing bugs without recent activity. Please submit a PR in case you are still interested in the feature.
