### ISSUE TITLE
Including headers adds exports

### ISSUE THREAD

**Issue by pdimov** [boostorg/container#185]
When I `#include <boost/json.hpp` on Windows, I get an import library created for my executable, with a bunch of Container exports there. I don't think this should happen. If these symbols are indeed in a library, they need to be marked as imported, not exported; and if they are not supposed to be in a library, they should be marked as visible, not as exported.

**Comment by igaztanaga** [comment]
Thanks for the report, you are righ, they should be marked as BOOST_SYMBOL_VISIBLE.
