### ISSUE TITLE
Heterogenous lookup for unordered_map

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/container#189]
New in C++20, this seems missing from Boost.Container?

**Comment by igaztanaga** [comment]
unordered_map is not part of Boost.Container, but Boost.Unordered...

**Comment by vinniefalco** [comment]
@igaztanaga Boost.Unordered is unmaintained. Is there any chance you could take it over? I mean, you are an expert of containers :) Or if you can't do it, could you please suggest someone who might be skilled enough to do it?
