### ISSUE TITLE
Possible copypaste typo.

### ISSUE THREAD

**Issue by pbalash0v** [boostorg/container#223]
Hi,
This looks like a copypaste typo:
https://github.com/boostorg/container/blob/f548e87cf5d5197992dd25c48a47e1db4924cde6/include/boost/container/throw_exception.hpp#L100

Presumably this should be:
```c++
typedef length_error length_error_t;
```

Regards,
Pavel.

**Comment by igaztanaga** [comment]
Thanks for the report!
