### ISSUE TITLE
variable set but not used in dlmalloc_ext_2_8_6.c

### ISSUE THREAD

**Issue by jefftrull** [boostorg/container#225]
The function `boost_cont_allocated_memory()` initializes and periodically updates a local variable `sum`, but never uses it for anything. This triggers warnings in some compilers and static analysis tools:

```c++
      size_t sum = mfree;          // ===> initialization
      msegmentptr s = &m->seg;
      while (s != 0) {
         mchunkptr q = align_as_chunk(s->base);
         while (segment_holds(s, q) &&
               q != m->top && q->head != FENCEPOST_HEAD) {
            size_t sz = chunksize(q);
            sum += sz;             // ===> update

```

**Comment by igaztanaga** [comment]
Thanks for the report, but I can't see how it's not used, "sum" is then assigned to nm.arena, which is returned
``nm.arena    = sum;``

**Comment by jefftrull** [comment]
That code is in `dlmalloc_2_8_6.c`, not `dlmalloc_ext_2_8_6.c`

**Comment by hdu-sdlzx** [comment]
@igaztanaga clang-15 complains about the following unused variables:
libs/container/src/dlmalloc_2_8_6.c:3991:7: warning: variable 'nfences' set but not used [-Wunused-but-set-variable]
  int nfences = 0;
      ^
In file included from libs/container/src/alloc_lib.c:24:
libs/container/src/dlmalloc_ext_2_8_6.c:1227:14: warning: variable 'sum' set but not used [-Wunused-but-set-variable]
      size_t sum = mfree;
             ^
2 warnings generated.
