### ISSUE TITLE
there is no warning number /4675/4284/4345

### ISSUE THREAD

**Issue by marakew** [boostorg/container#237]
config_begin.hpp(25): warning C4619: #pragma warning: there is no warning number '4284'
config_begin.hpp(28): warning C4619: #pragma warning: there is no warning number '4345'
config_begin.hpp(42): warning C4619: #pragma warning: there is no warning number '4675'

add check about BOOST_MSVC some warn seems removed by msvc

**Comment by igaztanaga** [comment]
Many thanks for the report!
