### ISSUE TITLE
hash_value overloads can probably be removed now

### ISSUE THREAD

**Issue by pdimov** [boostorg/container#256]
ContainerHash now has generic support for ranges, contiguous ranges and unordered ranges, so `boost::hash` should work for the containers as-is, without the need for library-provided `hash_value` overloads.

I don't see tests exercising `boost::hash` though, so it might be a good idea to add those first.

**Comment by igaztanaga** [comment]
hash_value overload was removed in commit https://github.com/boostorg/container/commit/0f448277c5a206f4872b6073dbe8ad7e754fd219
