### ISSUE TITLE
dtl vs std pair

### ISSUE THREAD

**Issue by psiha** [boostorg/container#264]
Any plans on finally ditching all the hundreds of LOCs for 'the pre-ancient days'/moving to at least cpp17?
Or at the very least using std::pair instead of dtl::pair - it leaks through in associative containers and adopted sequences?

**Comment by igaztanaga** [comment]
This does not seem a bug report, I'm afraid. In any case, starting from commit:

https://github.com/boostorg/container/commit/20ad12f20e661978e90dc7f36d8ab8ac05e5a5a9

dtl::pair is not used in the implementation for C++11 and later compilers
