### ISSUE TITLE
Support 'pure' (single pass) input_iterators

### ISSUE THREAD

**Issue by psiha** [boostorg/container#272]
Current assign() implementation from iterator pairs is broken for single-pass iterators (https://en.cppreference.com/w/cpp/iterator/input_iterator) since it assumes that the iterators satisfy at least the forward-iterator requirements (w/o checking those).

**Comment by igaztanaga** [comment]
Boost.Container, at least sequence containers should suppor assign from input iterators and that is tested in the library tests. Do you have an example that can reproduce the problem?

**Comment by igaztanaga** [comment]
Closing this issue as assign from input iterator is already checked.

**Comment by psiha** [comment]
> Boost.Container, at least sequence containers, should support "assign" from input iterators and that is tested in the library tests. Do you have an example that can reproduce the problem?

See here https://github.com/microsoft/STL/blob/b191409cec71aa837072a5d1ebafb041989c71dd/stl/inc/vector#L1245
...you don't handle the final else 'uncounted range' case.

**Comment by igaztanaga** [comment]
It's implemented using overloads and SFINAE. The function for input iterators is this:

https://github.com/boostorg/container/blob/develop/include/boost/container/vector.hpp#L1320

**Comment by igaztanaga** [comment]
Closing this issue as input iterators are implemented and and tested (https://github.com/boostorg/container/blob/develop/test/vector_test.hpp#L491)
