### ISSUE TITLE
Forward declarations of std types cause compilation errors on some platforms

### ISSUE THREAD

**Issue by Rottbott** [boostorg/container#292]
When compiling for a well-known console platform using C++20, the standard library implementation uses an inline namespace for versioning. This conflicts with the forward declarations in [`boost/container/detail/std_fwd.hpp`](https://github.com/boostorg/container/blob/develop/include/boost/container/detail/std_fwd.hpp) and results in names being ambiguous (e.g. `std::less` vs `std::some_inline_namespace::less`).

I believe Boost is at fault here because forward declaring `std` types is not allowed; perhaps this is one reason why. Although it may hurt compile times, in order to use Boost on this platform it's necessary to include the real headers rather than forward declaring. This behaviour should be removed, or at least made optional.

**Comment by igaztanaga** [comment]
This forward declaration is not allowed, but it's been practical for many years. I would much prefer to support your platform is possible. Can you give information about the compiler and the standard library implementation/headers. Or/and a patch? Usually inline namespaces are behind a macro that could be detected and used...

**Comment by Rottbott** [comment]
As it's a proprietary platform I'm not sure what I'm allowed to share, but I'll risk saying that the compiler is a Clang variant and `__PROSPERO__` is always defined. I was able to compile the library successfully with this modification:
```diff
//                        Standard predeclarations
//////////////////////////////////////////////////////////////////////////////

+#if __PROSPERO__
+#include <functional>
+#include <iterator>
+#include <memory>
+#include <string>
+#include <utility>
+#else
+
#include <boost/move/detail/std_ns_begin.hpp>
BOOST_MOVE_STD_NS_BEG
```
...
```diff
BOOST_MOVE_STD_NS_END
#include <boost/move/detail/std_ns_end.hpp>

+#endif // __PROSPERO__
+
#endif //#ifndef BOOST_CONTAINER_DETAIL_STD_FWD_HPP
```

It would be nicer if there's a generic way to detect the presence of an inline namespace, but I don't know how to go about it. If you want to simulate the errors, you can do so easily on any platform by declaring the following prior to including `std_fwd.hpp`:
```c++
namespace std
{
	inline namespace test
	{
		template<typename T> struct less;
	}
}
```

**Comment by Rottbott** [comment]
After trawling through system headers, I've found a more robust fix which should work with any environment using a Dinkumware stdlib. This involves a patch to [`boost/move/detail/std_ns_begin.hpp`](https://github.com/boostorg/move/blob/develop/include/boost/move/detail/std_ns_begin.hpp), so perhaps I should create a new issue and/or PR in that library instead? At any rate, this works:
```diff
#elif defined(BOOST_GNU_STDLIB) && defined(_GLIBCXX_BEGIN_NAMESPACE)  //GCC >= 4.2
   #define BOOST_MOVE_STD_NS_BEG _GLIBCXX_BEGIN_NAMESPACE(std)
   #define BOOST_MOVE_STD_NS_END _GLIBCXX_END_NAMESPACE
+#elif defined(_YVALS) // Dinkumware
+   #define BOOST_MOVE_STD_NS_BEG _STD_BEGIN
+   #define BOOST_MOVE_STD_NS_END _STD_END
#else
-   #if defined(_MSC_VER) && (_MSC_VER >= 1915)
-      #pragma warning (push)
-      #pragma warning (disable : 4643) // Forward declaring 'X' in namespace std is not permitted by the C++ Standard
-   #endif
-
   #define BOOST_MOVE_STD_NS_BEG namespace std{
   #define BOOST_MOVE_STD_NS_END }
#endif
+
+   #if defined(_MSC_VER) && (_MSC_VER >= 1915)
+      #pragma warning (push)
+      #pragma warning (disable : 4643) // Forward declaring 'X' in namespace std is not permitted by the C++ Standard
+   #endif
```

For some reason I don't understand, for this to work on MSVC I also had to undefine these in `std_ns_end.hpp`, which I assume is no bad thing anyway:
```diff
#ifdef BOOST_MOVE_STD_NS_GCC_DIAGNOSTIC_PUSH
   #pragma GCC diagnostic pop
   #undef BOOST_MOVE_STD_NS_GCC_DIAGNOSTIC_PUSH
#elif defined(_MSC_VER) && (_MSC_VER >= 1915)
   #pragma warning (pop)
#endif   //BOOST_MOVE_STD_NS_GCC_DIAGNOSTIC_PUSH
+
+#undef BOOST_MOVE_STD_NS_BEG
+#undef BOOST_MOVE_STD_NS_END
```

**Comment by igaztanaga** [comment]
Many thanks for your help. I've committed the suggested patch to Boost.Move.
