### ISSUE TITLE
[1.86] Bug in `small_vector::swap`

### ISSUE THREAD

**Issue by Morddin** [boostorg/container#295]
In the following code, the assertion fails:
```cpp
#include <boost/container/small_vector.hpp>
#include <cassert>

int main()
{
    auto v1 = boost::container::small_vector<int, 4>{0, 1, 2, 3, 4};
    auto v2 = boost::container::small_vector<int, 4>{5};
    v1.swap(v2);
    assert(v1[0] == 5);
}
```

A quick look makes me think that `this->priv_raw_begin()` should be replaced with `intmem.priv_raw_begin()` in the following two places:

https://github.com/boostorg/container/blob/83b8d5748dd93617bec92b1b31800213167a5cb9/include/boost/container/vector.hpp#L2767-L2768
https://github.com/boostorg/container/blob/83b8d5748dd93617bec92b1b31800213167a5cb9/include/boost/container/vector.hpp#L2778-L2780

**Comment by igaztanaga** [comment]
Many thanks for the report and the bug analysis!
