### ISSUE TITLE
`pmr::monotonic_buffer_resource::allocate()` can return a pointer to freed memory after `release()` is called

### ISSUE THREAD

**Issue by nickhutchinson** [boostorg/container#65]
As implemented, calling `release()` on a `pmr::monotonic_buffer_resource` leaves it in an inconsistent state, and this means calling `allocate()` can return a pointer to memory freed by the call to `release()`.

The 1.65.1 implementation of `release()` only resets one of the member variables:
```
void monotonic_buffer_resource::release() BOOST_NOEXCEPT
{  m_memory_blocks.release();  }
```

The member variables `m_current_buffer` and `m_current_buffer_size` (used in `do_allocate()`) are untouched.

**Comment by igaztanaga** [comment]
The commit leaves the monotonic buffer as default-constructed. Thanks for the report.
