### ISSUE TITLE
Pointer cast in copy_n_and_update function will break the strict-aliasing rule

### ISSUE THREAD

**Issue by westion717** [boostorg/container#67]
https://github.com/boostorg/container/blob/9137957672d122c464df8779be506436f88e27f5/include/boost/container/detail/advanced_insert_int.hpp#L385

A pointer cast above in copy_n_and_update function will break the strict-aliasing rule, and will get undefined behavior with aggressive optimization

**Comment by igaztanaga** [comment]
I've updated Boost.Move's aligned storage to use an internal char array:

https://github.com/boostorg/move/commit/a296628ce329a09c86a4e1bcdc306134f445568b

I've modified Boost.Container to use this member as placement new target in commit:

https://github.com/boostorg/container/commit/f0736ba73acb33b785f9e556c57b5f546aed6ddf

Let me know if this fixes the issue.

**Comment by igaztanaga** [comment]
The commit fixes the warning but the aliasing warning with aligned storage might be a bug as reported by GCC issues:

GCC 6: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70054
GCC 7: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80593

**Comment by westion717** [comment]
The fix can not fix aliasing breaking issue, please reopen it.
