### ISSUE TITLE
[Feature Request] Templated lookup methods in associative containers

### ISSUE THREAD

**Issue by Lastique** [boostorg/container#69]
C++14 added `find`/`lower_bound`/`upper_bound`/`equal_range`/`count` methods that accept a templated argument instead of a value of `key_type`. This is useful if the keys can be ordered against objects of different types (e.g. when the key is `std::string` and the argument is a `std::string_view`).

Please, add similar overloads to the associative containers in Boost.Container: `flat_set`, `flat_multiset`, `flat_map`, `flat_multimap`, `set`, `multiset`, `map`, `multimap`.

**Comment by igaztanaga** [comment]
Better late than never, requested many years ago:

https://svn.boost.org/trac10/ticket/11780

Fixed in commit:

https://github.com/boostorg/container/commit/48c21e3187cd95b42803efe297842b52c896090e

 Many thanks for the report.

**Comment by Lastique** [comment]
A friendly reminder to merge this to master before 1.68.

**Comment by igaztanaga** [comment]
Thanks for the reminder, just merged.
